apiVersion: v1
kind: Service
metadata:
  name: falco
  namespace: audit-ledger-security
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/part-of: audit-ledger
    app.kubernetes.io/component: runtime-security
spec:
  selector:
    app.kubernetes.io/name: falco
    app.kubernetes.io/part-of: audit-ledger
  ports:
    - name: metrics
      port: 8765
      targetPort: metrics
      protocol: TCP
